### ISSUE TITLE
nb_conda_kernels does not set the kernel to the correct  active environment

### ISSUE THREAD

**Issue by guyLee687** [anaconda/nb_conda_kernels#271]
It looks like https://github.com/anaconda/nb_conda_kernels/blob/04c5fc605c08a4ced0cc45d2a6507dea40897600/nb_conda_kernels/runner.py#L32

![image](https://github.com/anaconda/nb_conda_kernels/assets/37250217/72947dc9-0821-4b3a-8a3c-c5449af524bf)

is trying to activate the environment in a subprocess and which isn't used in when running kernelspec args.

**Comment by mcg1969** [comment]
I'm afraid I don't understand this issue as stated. I'm going to close it, but please feel free to re-open if you can provide more specific details about what you think is occurring, and what _should_ be happening instead.
